pipeline {
    agent {
        docker {
            image 'python:3.10'
            args '-u root'
            reuseNode true
            registryUrl 'https://index.docker.io/v1/'
            registryCredentialsId 'docker-hub-token'
        }
    }
    environment {
        GITHUB_CREDENTIAL = crendentials('github-token')
    }
    triggers {
        githubPush()
    }
    options {
        timestamps()
        timeout(time: 5, unit: 'MINUTES')
    }
    stages {
        stage('pip install') {
            steps {
                echo 'requirements.txt reading...'
                sh 'pip install -r requirements.txt'
                echo 'pip install done.'
                echo 'flask install success!!'
            }
        }
        stage('flask run') {
            options {
            timeout(time: 1, unit: 'MINUTES')
        }
            steps {
                echo 'flask ready'
                sh 'python src/main.py &'
                echo 'flask running'
            }
        }
        stage('endpoint test') {
            steps {
                echo 'http://localhost:5000/ connect...'
                sh 'curl -s localhost:5000'
            }
        }
        stage('github create release') {
            steps {
                sh """
                curl -sSL \
                      -X POST \
                      -H 'Accept: application/vnd.github+json' \
                      -H 'Authorization: Bearer GITHUB_CREDENTIAL_PSW' \
                      -H 'X-GitHub-Api-Version: 2022-11-28' \
                      https://api.github.com/repos/minjunkim5876/flask-cicd/releases \
                      -d \"{'tag_name':'v1.0.0',
                      'target_commitish':'main',
                      'name':'v1.0.0',
                      'body':'Description of the release',
                      'draft':false,
                      'prerelease':false,
                      'generate_release_notes':false}\"
                """
            }
        }
    }
}
    
