pipeline {
    agent {
        docker {
            image 'python:3.10'
            args '-u root'
            reuseNode true
            registryUrl 'https://index.docker.io/v1/'
            registryCredentialsId 'docker-hub-token'
        }
    }
    environment {
        GITHUB_CREDENTIAL = credentials('github-token')
    }
    triggers {
        githubPush()
    }
    options {
        timestamps()
        timeout(time: 5, unit: 'MINUTES')
    }
    stages {
        stage('pip install') {
            steps {
                echo 'requirements.txt reading...'
                sh 'pip install -r requirements.txt'
                echo 'pip install done.'
                echo 'flask install success!!'
            }
        }
        stage('flask run') {
            options {
            timeout(time: 1, unit: 'MINUTES')
        }
            steps {
                echo 'flask ready'
                sh 'python src/main.py &'
                echo 'flask running'
            }
        }
        stage('endpoint test') {
            steps {
                echo 'http://localhost:5000/ connect...'
                sh 'curl -s localhost:5000'
            }
        }
        stage('github create release') {
            steps {
                script{
                   def response = sh(script: """
                curl -sSL \
                      -X POST \
                      -H "Accept: application/vnd.github+json" \
                      -H "Authorization: Bearer ${GITHUB_CREDENTIAL_PSW}" \
                      -H "X-GitHub-Api-Version: 2022-11-28" \
                      https://api.github.com/repos/minjunkim5876/flask-cicd/releases \
                      -d '{
                      "tag_name":"v1.1.0",
                      "target_commitish":"main",
                      "name":"v1.1.0",
                      //버전설명 적는 곳
                      "body":"Description of the release",
                      "draft":false,
                      "prerelease":false,
                      "generate_release_notes":false
                      }'
                """, returnStdout: true)
                    sh "echo '$response'"

                    def json = readJSON text: "$response"
                    def id = json.id
                    sh  'tar -zcvf flask-web.tar.gz ./src'

                    sh """
                        curl -L \
                          -X POST \
                          -H "Accept: application/vnd.github+json" \
                          -H "Authorization: Bearer ${GITHUB_CREDENTIAL_PSW}" \
                          -H "X-GitHub-Api-Version: 2022-11-28" \
                          -H "Content-Type: application/octet-stream" \
                          "https://uploads.github.com/repos/minjunkim5876/flask-cicd/releases/${id}/assets?name=flask-web.tar.gz" \
                          --data-binary "@flask-web.tar.gz"
                    """
                }
            }
        }
    }
}
    
